# Generated by Django 6.0.5 on 2026-05-26 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nre', models.CharField(max_length=10, unique=True)),
                ('naran_estudante', models.CharField(max_length=100)),
            ],
        ),
    ]
