# Generated by Django 6.0.5 on 2026-05-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='hela_fatin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudante',
            name='nu_telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudante',
            name='sexu',
            field=models.CharField(choices=[('mane', 'mane'), ('feto', 'feto')], default=0, max_length=4),
            preserve_default=False,
        ),
    ]
