# Generated by Django 6.0.5 on 2026-07-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademiku', '0001_initial'),
        ('estudante', '0002_estudante_hela_fatin_estudante_nu_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akademiku.turma'),
        ),
    ]
