# Generated by Django 6.0.5 on 2026-07-10 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nre', models.CharField(max_length=10, unique=True)),
                ('naran_docente', models.CharField(max_length=100)),
                ('hela_fatin', models.CharField(blank=True, default='', max_length=50)),
                ('nu_telefone', models.CharField(max_length=15)),
                ('sexu', models.CharField(choices=[('mane', 'Mane'), ('feto', 'Feto')], max_length=4)),
                ('materia', models.CharField(blank=True, default='', max_length=100)),
                ('data_kontratu', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
