# Generated by Django 6.0.5 on 2026-07-12 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('estudante', '0002_estudante_hela_fatin_estudante_nu_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naran_turma', models.CharField(max_length=50, unique=True)),
                ('ano_letivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naran_disciplina', models.CharField(max_length=100, unique=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='docente.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliasaun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=4)),
                ('data', models.DateField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliasaun', to='estudante.estudante')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliasaun', to='akademiku.disciplina')),
            ],
            options={
                'verbose_name': 'Avaliasaun',
                'verbose_name_plural': 'Avaliasaun',
                'unique_together': {('estudante', 'disciplina', 'data')},
            },
        ),
    ]
