# Generated by Django 6.0.5 on 2026-07-16 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docente', '0001_initial'),
        ('estudante', '0002_estudante_hela_fatin_estudante_nu_telefone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naran_turma', models.CharField(max_length=50)),
                ('ano_letitva', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naran_disciplina', models.CharField(max_length=100)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliasaun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=4)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudante.estudante')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademiku.disciplina')),
            ],
        ),
    ]
